[package]
name = "discord-telegram-forwarder"
version = "0.1.0"
authors = ["Or <10655932+Orbsynated@users.noreply.github.com>"]
repository = "https://github.com/Orbsynated/discord-telegram-forwarder/"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

