discord-token: test
telegram-bot-token: test
verbosity-level: DEBUG
# Timezone format is from the tz database. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Look for the 'TZ database name' column
time-zone: America/New_York
filter:
  # discord server name
  - disocrd-server-name-or-id: The Kings
    # Is server name an ID or name (default: false)
    server-id: false
    # User Ids to accept messages
    accept-users:
      - 987654321
      - 132456798
