discord-token: test
telegram-bot-token: test
# Default is Info
verbosity-level: DEBUG

# Timezone format is from the tz database. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Look for the 'TZ database name' column
# Default is UTC
time-zone: UTC
filter:
  # discord server name
  - discord-server-id: 1234
    # Due to discord api limitation, server name cannot be fetched if self-bots are used
    discord-server-name: The Kings
    # User Ids to accept messages
    accept-users:
      - 987654321
      - 132456798
